name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: generate image tag
      run: TAG="ghcr.io/$GITHUB_ACTOR/logo-mqtt:$(date +%s)"
      
    - name: login
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      
    - name: build image
      run: docker build . --tag $TAG
      
    - name: push image
      run: docker push $TAG
