name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      env: 
        TAG: ghcr.io/thosch1800/logo-mqtt:$(date +%s)
    
    - name: print tag
      run: echo ${{ env.TAG }}
      
    - name: login
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u thosch1800 --password-stdin
      
    - name: build image
      run: docker build . --tag ${{ env.TAG }}
      
    - name: push image
      run: docker push ${{ env.TAG }}
